### ISSUE TITLE
izmjena Tweetova?

### ISSUE THREAD

**Issue by debeluziju** [udruga-biom/puobot#14]
Tweetovi su formatirani na način

godina-_skraćeni naziv dokumenta_-oblik dokumenta (rješenje, informacija, etc.)-puni naziv dokumenta-link

Može li se izbaciti ovaj dio u italicu, jer ima i punio naziv kasnije koji uglavnom ne stane, pa se dogodi da imamo dva jednako kratka naziva dokumenta... S izbacivanjem toga bi stala i lokacija koja je često u nazivu...

Valjda sam jasan..

**Comment by narimiran** [comment]
> Može li se izbaciti ovaj dio u italicu

Moze.

Kad smo vec kod oslobadjanja mjesta - trebaju li tvitovi na pocetku imati godinu, ili bi bilo bolje  tih 5 znakova pustiti za puni naziv?

**Comment by debeluziju** [comment]
Zec nam treba za ovo pitanje. Ja brijem da nam ne treba jer je to samo
godina kad je objavljena informacija što je u biti očito...




Vedran Lucić
Programme Manager, Association BIOM - BirdLife in Croatia
p: +385 1 410 0018 m: +385 95 905 9948 a: Preradovićeva 34, 10000 Zagreb,
Croatia
s: www.biom.hr e: vedran.lucic@biom.hr



2017-04-02 14:33 GMT+02:00 narimiran <notifications@github.com>:

**Comment by narimiran** [comment]
> Ja brijem da nam ne treba

Meni se isto tako cini, ali pricekajmo @mzec da da presudu.

**Comment by mzec** [comment]
Hvala na feedbacku ljudi! :grinning: 

> Tweetovi su formatirani na način
> godina-skraćeni naziv dokumenta-oblik dokumenta (rješenje, informacija, etc.)-puni naziv dokumenta-link
> Može li se izbaciti ovaj dio u italicu, jer ima i punio naziv kasnije koji uglavnom ne stane, pa se dogodi da imamo dva jednako kratka naziva dokumenta... S izbacivanjem toga bi stala i lokacija koja je često u nazivu...

Drugo polje u tablici nije skraćeni naziv dokumenta nego puni naziv zahvata, koji se ponekad uopće ne spominje u punom imenu dokumenta, na primjer: 

- PUO postupci 2014.
- Modernizacija postojećeg i izgradnja drugog kolosijeka željezničke pruge M201 na dionici Križevci - Koprivnica - državna granica
- PUO javni uvid
- Ne-tehnički sažetak Studije [PDF]
- http://mzoip.hr/doc/ne-tehnicki_sazetak_studije_8.pdf

Istina je da često dolazi do duplanja jer se ime zahvata ponavlja u imenu dokumenta, ali što god da izbacimo iz tweeta mogle bi biti potencijalno bitne informacije. Činjenica je da twitter zbog limita na 140 znakova nije idealan za ovu potrebu, ali zato će iduća verzija imati suvisliji frontend, a kad napišemo bolji parser za podatke bit će relativno lako poboljšati i format tweetova da budu informativniji.

> Ja brijem da nam ne treba jer je to samo godina kad je objavljena informacija što je u biti očito...

Godina na početku tweeta za PUO i OPUO dokumente nije godina kad je donesen dokument, nego godina kad je pokrenut postupak, što nije uvijek očito. Taj prvi dio u biti govori gdje se taj postupak nalazi na stranici MZOIE. Ako je rješenje izdano jučer za postupak koji je pokrenut 2015., bit će na njihovoj stranici pod 'PUO postupci 2015'. Ponavljam, twitter je privremeno rješenje dok ne složimo stranicu.

**Comment by narimiran** [comment]
> Istina je da često dolazi do duplanja jer se ime zahvata ponavlja u imenu dokumenta
> (...)
> kad napišemo bolji parser za podatke bit će relativno lako poboljšati i format tweetova da budu informativniji

Dok ne dodje suvisliji frontend, mogu probati sloziti neku verziju u kojoj provjerava dolazi li do duplanja, i onda ako je to slucaj - mice duplani dio (onaj koji @debeluziju preporuca da se izbaci), a u suprotnom ostavlja sve kako je i do sad?
